---
- name: Verify
  hosts: all
  tasks:
    - name: OpenBSD | Java should be functionnal
      ansible.builtin.command: java -version
      register: java_result
      changed_when: false

    - name: OpenBSD | Verify commands outputs
      ansible.builtin.assert:
        that:
          - java_result.rc == 0
        success_msg: "All tests passed"
