---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: linux
    image: ${namespace:-diodonfrost}/${image:-ansible-ubuntu:22.04}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    cgroupns_mode: host
    privileged: yes
    pre_build_image: yes
    env:
      java_version: "${java_version:-latest}"
provisioner:
  name: ansible
verifier:
  name: ansible
